### ISSUE TITLE
A proposed format for district data

### ISSUE THREAD

**Issue by eyeseast** [LearningLab/public-schools#1]
Here's a proposed data layout, in YAML, for districts. This is just basic info. What else do we need?

``` yaml
- id:
    dese: <MA DESE ID>
    nces: <NCES ID>
    other: <some other ID used somewhere else>
 name: Full School Name
 grades:
    start: k
    end: 6
    range: [k, 1, 2, 3, 4, 5, 6]
 location:
    address1: 1 Main St
    address2: Suite 404
    city: Boston
    state: MA
    county: Suffolk
    lat: <float>
    lng: <float>
 contact:
    name: Gary Chalmers
    title: superintendent
    email: gchalmers@springfieldpublicschools.org
    phone: 617-555-1234
    fax: 617-555-7890

```
